Terraform
Azure/azlustre pull request #1
Opened 2021-02-24 07:44 UTC by ranieuwe

### Terraform templates for deploying Lustre on Azure

- Sets up a MGS and MDS node with a P30 disk attached to it
- Sets up multiple OSS nodes with one more disks attached to it. Configured with mdadm they are exposed as OSS nodes to the MGS
- Sets up a jumpbox that has the Lustre filesystem automatically mounted

Default sizing is using 2 D32s_v3 with 4 P30 disks, yielding 4TB of Lustre with 3.8TB usable per node for a total of 7.6TB. This deployment uses your local SSH keys to set up the access. How to deploy (README next):

1. Run ```az login```
2. In the directory, run ```terraform plan```
3. Apply the plan using ```terraform apply -parallelism=30``` you can change the parallelism. A value of $oss_nodes * $disks_per_oss is recommended (e.g. 12x4 => 48).
4. Make coffee, ~10 min later run ```az vm list-ip-addresses -o table``` and note the IP of the jumpbox.
5. Get on the jumpbox with ```ssh lustre@<ip>``` and check out the lustre filesystem on ```/lustre``` or checkout ```lfs df -h```

To SSH to the OSS or MGS nodes, please scp/sftp your private key to the jumpbox and hop from there to the node.

2021-02-24 09:19 UTC, edwardsp requested changes
please add a readme to show the current state (e.g. work in progress to make this more generalised).  Thanks!

2021-02-24 09:19 UTC, edwardsp commented on terraform/scripts/lustre.tpl
> +node_index=$((${index}))
do you need to put this in "$(( ))" as no arithmetic is performed?

2021-02-24 09:19 UTC, edwardsp commented on terraform/scripts/lustre.tpl
> +	# TODO Make this dynamic?
making this dynamic would be good, especially since there are VM types without an ephemeral disk now (e.g. Dv4) and so the first disk would be /dev/sdb.

2021-02-25 00:55 UTC, ranieuwe commented on terraform/scripts/lustre.tpl
> +node_index=$((${index}))
Resolved

2021-02-25 09:59 UTC, edwardsp approved these changes
looks good

2021-02-25 10:00 UTC, merged